# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NEC TV Control
version: "1.0.10"
slug: hass-nec-control
description: Control your NEC TV via network commands
url: "https://github.com/MichalTorma/ha-repository"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8124/tcp: 8124
map:
  - share:rw
options:
  tv_ip: "192.168.1.150"
  tv_port: 7142
schema:
  tv_ip: "str"
  tv_port: "int?"
# image: "ghcr.io/your-repo/{arch}-addon-hass-nec-control"
